INSERT INTO USER (USERNAME, PASSWORD) VALUES ('yusufadmin', '$2a$11$.I4NwUbVq47mKTn4TV/m0euqebiNKaX58Q6msjpadByrq6GzJtORa');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('yusufuser', '$2a$11$jKdScAOssp2L5yxdRMPy1uUZe8pbkRuGNbRIwl0npweojdraZ9vQe');

INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('yusufadmin', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('yusufuser', 'USER');